### ISSUE TITLE
Suggestion: These Vehicles

### ISSUE THREAD

**Issue by Namakarmon** [BrassGoggledCoders/VehicularEngineering#1]
hi can you pleas add planes. I think the parts should be small multi-block structure so say for example :
the left wing would be assembled and could be modified in the engineers workbench so say you only had one gun you could only put only one gun on the one wing and then place all the parts together so the wings and engine ect.

So could you plz consider this sugestion siriously thanks HappyPineapple_🍍

**Comment by SkySom** [comment]
I'm gonna say no.

**Comment by Namakarmon** [comment]
Kk may I just say I fully support you in this add-on?
