### ISSUE TITLE
Grappling Bolt

### ISSUE THREAD

**Issue by Namakarmon** [BrassGoggledCoders/VehicularEngineering#2]
Hi me again filling your to do list and ideas could you have a wrist rod shooter that has 2 tier's. 1 tier being hemp fibre and tier 2 being steel cabling. So it would be crafted something like this, two hemp fibers, iron or steel rod steel mechanical component and a HV wire connector. Hemp fibre would last once and steel 1000 times. Would require capacitor backpack to function as it does not have an internal power storage.

**Comment by SkySom** [comment]
I don't see how this works at all with VE's Theme.
